<?php
return array(
    'Contenido_Servicio'=>'Services',
    'Contenido_nosotros'=>'
    We are a company dedicated to the hospitality industry, which offers a service of excellence and quality to customers; for this we have trained and responsible personnel. The different types of rooms are: single, double and matrimonial rooms; with the following services: Free breakfast, Internet - Wifi, cable TV, hot water 24 hours a day, private bathroom and free carport.',
    'Contenido_turismo_salud'=>'Health tourism, is that people who feel some disease and want to restore their health through alternative therapies, complementary, traditional or energetic can be treated with any of these. We also perform medical laser therapy.',	
    'Contenido_biografia'=>'Inocencia Alvitez Llaycay, was born on December 28, 1955, in a populated center of San Mateo, district of Tintay province of Aymaraes, department of Apurímac being the third daughter of Angela Alvitez Robles and of Gabino Huanca Anampa, in a moment of moral abandonment and material, lives in the orphanage of Abancay and later in the orphanage of Chuquibambilla, Grau Apurímac; they discover at 8 years old the natural gift of healing and healing in the city of Abancay. He completed his higher studies at the La Salle de Abancay technological institute and worked 20 years as a teacher and is currently engaged in hospitality and health tourism companies, with extensive experience in the treatment of health in alternative, complementary therapies. energetic and traditional.',		
    'Contenido_habitacionsimple'=>'The Abancay hotel offers several types of rooms and one of them are simple rooms so that our clients feel at home.',				
    'Contenido_habitaciondoble'=>'The Abancay hotel offers several types of rooms and one of them are double rooms so that our clients feel at home.',	
    'Contenido_habitacionmatrimonial'=>'The Abancay hotel offers several types of rooms and one of them are marriage rooms so that our clients feel at home.',
    'Contenido_terapiaalternativa'=>'A true alternative to restore the health of people through elements,  vegetables products, purely natural minerals; between the plants, roots, barks, plants of natural plants, which applies a request of people suffering from a disease wishing to leave the allopathic medicine.',
    'Contenido_terapiacomplementaria'=>'They are the therapies that complement medical work as an assistant to restore the health of people. Allopathic medicine also makes medicine complementary to natural work, as desired by the client.',
    'Contenido_terapiatradicional'=>'They are medicines that until today are still practiced according to the knowledge and praxis of tradition in tradition, are knowledge of our ancestors that today are still practiced; with the use of different minerals in cases where people have suffered, violence, overturning, violence of murder, assaults or any attempt of suicide etc, or people who have lost their reason',	
    'Contenido_terapiaenergetica'=>'It is a type of medicine with immediate result in cases of stress, ailments, despair, people with a pale face among others; each 5 minute session.'    
);