<?php
return array(
    'Contenido_Servicio'=>'Services',
	'Contenido_turismo_salud'=>'HEALTH TOURISM, IS THAT PEOPLE WHO FEEL SOME DOLENCE AND WANT TO RESTRICT YOUR HEALTH THROUGH ALTERNATIVE, COMPLEMENTARY, TRADITIONAL OR ENERGY THERAPIES CAN BE TREATED WITH ANY OF THESE. WE ALSO REALIZE THERAPY WITH LASER MEDICAL.',	
    'Contenido_biografia'=>'INNOCENCE ALVITEZ LLAYCAY, WAS BORN ON DECEMBER 28, 1955, IN A POPULAR CENTER OF SAN MATEO, DISTRICT OF TINTA AND PROVINCE OF AYMARAES, APURIMAC DEPARTMENT BEING THE THIRD DAUGHTER OF ANGELA ALVITEZ ROBLES AND GABINO HUANCA ANAMPA. IN A MOMENT OF MORAL AND MATERIAL ABANDONMENT, HE LIVES IN THE ORANELINE OF ABANCAY AND AFTERWARD IN THE ORPHANAGE OF CHUQUIBAMBILLA, GRAU APURÍMAC. THE NATURAL GIFT OF HEALING AND CURE IN THE CITY OF ABANCAY IS DISCOVERED AT 8 YEARS OLD. MADE HIS SUPERIOR STUDIES AT LA SALLE DE ABANCAY TECHNOLOGY INSTITUTE AND WORK 20 YEARS AS A TEACHER AND CURRENTLY DEDICATES TO HOTELS AND TOURISM COMPANIES OF HEALTH, WITH A GREAT EXPERIENCE IN HEALTH TREATMENT IN ALTERNATIVE, COMPLEMENTARY THERAPIES, ENERGY AND TRADITIONAL.',		
    'Contenido_habitacionsimple'=>'The Abancay hotel offers several types of rooms and one of them are simple rooms so that our clients feel at home.',				
    'Contenido_habitaciondoble'=>'The Abancay hotel offers several types of rooms and one of them are double rooms so that our clients feel at home.',	
    'Contenido_habitacionmatrimonial'=>'The Abancay hotel offers several types of rooms and one of them are marriage rooms so that our clients feel at home.',
    'Contenido_terapiaalternativa'=>'A true alternative to restore the health of people through elements,  vegetables products, purely natural minerals; between the plants, roots, barks, plants of natural plants, which applies a request of people suffering from a disease wishing to leave the allopathic medicine.',
    'Contenido_terapiacomplementaria'=>'They are the therapies that complement medical work as an assistant to restore the health of people. Allopathic medicine also makes medicine complementary to natural work, as desired by the client.',
    'Contenido_terapiatradicional'=>'They are medicines that until today are still practiced according to the knowledge and praxis of tradition in tradition, are knowledge of our ancestors that today are still practiced; with the use of different minerals in cases where people have suffered, violence, overturning, violence of murder, assaults or any attempt of suicide etc, or people who have lost their reason',	
    'Contenido_terapiaenergetica'=>'It is a type of medicine with immediate result in cases of stress, ailments, despair, people with a pale face among others; each 5 minute session.'    
);