<?php
return array(	
    'Contenido_Servicio'=>'Servicios',
   
    'Contenido_nosotros'=>'Somos una empresa dedicada a la industria de la  hotelería, que brinda un servicio de excelencia y calidad a los clientes; para ello contamos con personal capacitado y responsable. Ofrecemos diferentes tipos de habitaciones las cuales son: habitaciones simples, dobles y matrimoniales;  con los siguientes servicios: Desayuno de cortesía, Internet – Wifi, televisión con cable, agua caliente las 24 horas del día, baño privado y cochera gratis.',
    'Contenido_biografia'=>'Inocencia Albites Llancay, nació el 28 de diciembre de 1955, en un centro poblado de San Mateo, distrito de Tintay provincia de Aymaraes, departamento de Apurímac siendo la tercera hija de Angel Albites Robles y de Gabina Huanca Anampa, en un momento de abandono moral y material, vive en el orfelinato de Abancay y posteriormente en el orfanato de Chuquibambilla, Grau Apurímac; le descubren a los 8 años el don natural de sanar y curar en la ciudad de Abancay. Realizó sus estudios superiores en el instituto superior pedagógico la Salle de Abancay y trabajo 20 años como docente y actualmente se dedica a las empresas de hotelería y turismo de la salud, con una gran experiencia en el tratamiento de la salud en las terapias alternativas, complementarias, energéticas y tradicionales.',		
    'Contenido_habitacionsimple'=>'El hotel Abancay, ofrece varios tipos de habitaciones y una de ellas son las habitaciones simples para que nuestros clientes se sientan como en su casa.',		
    'Contenido_habitaciondoble'=>'El hotel Abancay, ofrece varios tipos de habitaciones y una de ellas son las habitaciones dobles para que nuestros clientes se sientan como en su casa.',	
    'Contenido_habitacionmatrimonial'=>'El hotel Abancay, ofrece varios tipos de habitaciones y una de ellas son las habitaciones matrimoniales para que nuestros clientes se sientan como en su casa.'	,
    'Contenido_terapiaalternativa'=>'Una verdadera alternativa para restablecer la salud de las personas a través de elementos, productos vegetales, minerales puramente naturales; entre ellas están las plantas, raíces cortezas, zumos de plantas naturales, la que se aplica a solicitud de las personas que padecen alguna dolencia deseando salir de la medicina alopática.',
    'Contenido_terapiacomplementaria'=>'Son las terapias que hacen complemento al trabajo médico como ayudante para restablecer la salud de las personas. La medicina alopática también hace de medicina complementaria al trabajo natural, según  como desee el cliente.',
    'Contenido_terapiatradicional'=>'Son medicinas que hasta hoy se siguen practicando de acuerdo al conocimiento y la praxis de tradición en tradición, son saberes de nuestros ancestros que hoy por hoy todavía se practican; con el uso de las diferentes minerales en casos de que las personas hayan sufrido, violencia, volcadura, violencias de asesinato, asaltos o algún intento de suicidio etc, o personas que hayan perdido la razón (orates).',
    'Contenido_terapiaenergetica'=>'Es un tipo de medicina de resultado inmediato en casos de estrés, dolencias, desesperaciones, personas que tengan cara pálida entre otros; cada sesión de 5 minutos',
    'Contenido_turismo_salud'=>'Son métodos, técnicas, paleativos o curativos para tratar y/o mejorar los distintos síntomas de las dolencias o enfermedades para la cual utiliza productos naturales en su estado puro que proviene directamente de la naturaleza, no son productos farmacológicos ni procesados quimicamente. Según la OMS, ésta se define como el conunto de conocimientos basados en las creencias y experiencias ancentrales. Estas prácticas terapeuticas requieren principalmente de productos minerales, vegetales, raices, tallos, flores y hojas cuya praxis y experiencia logre a lo largo de mis larguísimos años.
    las cuales se utilizan de acuerdo a las necesidades y exigencias mediante ingestión o por la piel. Primeramente al paciente se le da a conocer todo lo que con el o ella se va a utilizar luego, con su pleno conocimiento si es el caso se aplica. Estas medicinas naturales previenen o curan las distintas dolencias modernas de este tiempo como es la diabetis, cáncer, artritis, reumatismo, estrés, ansiedad, depresión, desarreglos emocionales y más dolencias que aquejan al ser humano toda ves que mi persona mantiene la dolencia del diabetis hace más de 15 años y así tenemos la amplia gama de medicinas como alternativas, complementarias, tradicionales y energéticas, esta ultima se puede realizar de dos maneras.',
    'Contenido_turismo_salud1'=>'1.- En forma silenciosa para lo que simplemente me ubico cerca de la persona que acepta sin pronunciar ni una sola palabra al concluir la persona 
    esta en condiciones de opinar sobre ella.',
    'Contenido_turismo_salud2'=>'2.- La terapia energética presencial se realiza con la persona que quiere recibir conversando con ella quien siente el ingreso de la energía y opina.',
    'Contenido_turismo_salud3'=>'3.- Terapia energética a distancia alrededor del mundo vía whatsaap o messenger, gracias al comentario de mi mejor amigo el señor cientifico aleman Harald Fertig (Veticure). Quien comentó acerca de mi persona en el circulo de medicos alemanes en las nuevas medicinas germánicas y dio mi whatsaap. Razón por la cual me llaman las personas de todas partes del mundo en el idioma español y reciben en sus países de origen la terapia energética a distancia.',
    'Contenido_turismo_abancay'=>'Turismo de salud sede Abancay',
    'Contenido_turismo_abancay1'=>'Promueve los conocimiento de los centros turisticos del departamento de Apurpimac. En Abancay, el santuario nacional del Ampay, la casa haciendode Illanya, el Puente colonial de Pachachaca, el Mirador y otros. La terapia energética se realizara en esos lugares.',
    'Contenido_turismo_abancay2'=>'En la provincia de Aymaraes, chalhuanca se visitara a las aguas termomedicinales de Pincahuacho, en este lugar se realizará la quiropraxia y masaje profesional (Con certificación)',
    'Contenido_turismo_abancay3'=>'En Curahuasi, se visitará el monolito de Saywite para realizar diferentes terapias',
    'Contenido_turismo_abancay4'=>'En curahuasi se visitara capitan Rumi "Mirador del cañon de Apurímac; observando el vuelo del condor."',
    'Contenido_turismo_Fines'=>'Los fines del turismo de Salud',
    'Contenido_turismo_Fines1'=>'1.-Revalorar los milenarios conocimientos ancentrales de las diferentes culturas en el Perú',
    'Contenido_turismo_Fines2'=>'2.-Repotenciar la enconomia de la región',
    'Contenido_turismo_Fines3'=>'3.-Inocencia Albites Llancay difundira las distintas terapias naturales a nivel local, regional, nacional e internacional a grupos de personas organizadas o no, repotenciando la economia en esas zonas'

);