<?php
return array(	
    'Contenido_Servicio'=>'Servicios',
    'Contenido_turismo_salud'=>'El turismo en salud, consiste en que personas que sienten alguna dolencia y que desean restablecer su salud a través de las terapias alternativas, complementarias, tradicionales o energéticas pueden hacerse tratar con alguna de éstas. También realizamos terapia con láser medical.',
    'Contenido_nosotros'=>'Somos una empresa dedicada a la industria de la  hotelería, que brinda un servicio de excelencia y calidad a los clientes; para ello contamos con personal capacitado y responsable. Ofrecemos diferentes tipos de habitaciones las cuales son: habitaciones simples, dobles y matrimoniales;  con los siguientes servicios: Desayuno de cortesía, Internet – Wifi, televisión con cable, agua caliente las 24 horas del día, baño privado y cochera gratis.',
    'Contenido_biografia'=>'Inocencia Albites Llancay, nació el 28 de diciembre de 1955, en un centro poblado de San Mateo, distrito de Tintay provincia de Aymaraes, departamento de Apurímac siendo la tercera hija de Angel Albites Robles y de Gabina Huanca Anampa, en un momento de abandono moral y material, vive en el orfelinato de Abancay y posteriormente en el orfanato de Chuquibambilla, Grau Apurímac; le descubren a los 8 años el don natural de sanar y curar en la ciudad de Abancay. Realizó sus estudios superiores en el instituto superior pedagógico la Salle de Abancay y trabajo 20 años como docente y actualmente se dedica a las empresas de hotelería y turismo de la salud, con una gran experiencia en el tratamiento de la salud en las terapias alternativas, complementarias, energéticas y tradicionales.',		
    'Contenido_habitacionsimple'=>'El hotel Abancay, ofrece varios tipos de habitaciones y una de ellas son las habitaciones simples para que nuestros clientes se sientan como en su casa.',		
    'Contenido_habitaciondoble'=>'El hotel Abancay, ofrece varios tipos de habitaciones y una de ellas son las habitaciones dobles para que nuestros clientes se sientan como en su casa.',	
    'Contenido_habitacionmatrimonial'=>'El hotel Abancay, ofrece varios tipos de habitaciones y una de ellas son las habitaciones matrimoniales para que nuestros clientes se sientan como en su casa.'	,
    'Contenido_terapiaalternativa'=>'Una verdadera alternativa para restablecer la salud de las personas a través de elementos, productos vegetales, minerales puramente naturales; entre ellas están las plantas, raíces cortezas, zumos de plantas naturales, la que se aplica a solicitud de las personas que padecen alguna dolencia deseando salir de la medicina alopática.',
    'Contenido_terapiacomplementaria'=>'Son las terapias que hacen complemento al trabajo médico como ayudante para restablecer la salud de las personas. La medicina alopática también hace de medicina complementaria al trabajo natural, según  como desee el cliente.',
    'Contenido_terapiatradicional'=>'Son medicinas que hasta hoy se siguen practicando de acuerdo al conocimiento y la praxis de tradición en tradición, son saberes de nuestros ancestros que hoy por hoy todavía se practican; con el uso de las diferentes minerales en casos de que las personas hayan sufrido, violencia, volcadura, violencias de asesinato, asaltos o algún intento de suicidio etc, o personas que hayan perdido la razón (orates).',
    'Contenido_terapiaenergetica'=>'Es un tipo de medicina de resultado inmediato en casos de estrés, dolencias, desesperaciones, personas que tengan cara pálida entre otros; cada sesión de 5 minutos'
);